version: '3.1'

services:
  db:
    container_name: ${NAME}-db
    image: postgres:${POSTGRES_VERSION}
    restart: always
    environment:
     - POSTGRES_USER=${DB_USER}
     - POSTGRES_PASSWORD=${DB_PASSWORD}
     - POSTGRES_DB=${DB_NAME}
    volumes:
    - ${DB_DATA}:/var/lib/postgresql/data/
    ports:
    - ${DB_PORT}:5432
  solr:
    container_name: ${NAME}-solr
    image: vzgreposis/mir-solr:${SOLR_VERSION}
    restart: always
    volumes:
    - ${SOLR_DATA}:/var/solr-data
    ports:
    - ${SOLR_PORT}:8983
  mir:
    container_name: ${NAME}-mir
    image: vzgreposis/mir:${MIR_VERSION}
    restart: always
    environment:
    - APP_CONTEXT=${APP_CONTEXT}
    - JDBC_NAME=${DB_USER}
    - JDBC_PASSWORD=${DB_PASSWORD}
    - JDBC_DRIVER=org.postgresql.Driver
    - JDBC_URL=jdbc:postgresql://db:5432/${DB_NAME}
    - SOLR_URL=http://solr:8983
    - SOLR_CORE=${SOLR_CORE}
    - SOLR_CLASSIFICATION_CORE=${SOLR_CLASSIFICATION_CORE}
    volumes:
    - ${MIR_HOME}:/mcr/home/
    - ${MIR_DATA}:/mcr/data/
    depends_on:
      - db
      - solr
    ports:
      - ${MIR_PORT}:8080
      - ${MIR_AJPPORT}:8009
